import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/components/layout.css',
                'resources/css/pages/admin-audit.css',
                'resources/css/pages/admin-departments.css',
                'resources/css/pages/auth-login.css',
                'resources/css/pages/auth-setup-password.css',
                'resources/css/pages/auth-welcome.css',
                'resources/js/pages/auth/experience.js',
                'resources/css/pages/board.css',
                'resources/css/pages/daily-logs.css',
                'resources/css/pages/board-admin.css',
                'resources/css/pages/admin-approvals.css',
                'resources/css/pages/work-board.css',
                'resources/css/pages/work-board-admin.css',
                'resources/css/pages/employees.css',
                'resources/css/pages/errors.css',
                'resources/css/pages/meetings.css',
                'resources/css/pages/mytasks.css',
                'resources/css/pages/notifications.css',
                'resources/css/pages/report-employee.css',
                'resources/css/pages/report-employees.css',
                'resources/css/pages/report-my.css',
                'resources/css/pages/report-operational.css',
                'resources/css/pages/report-organization.css',
                'resources/css/pages/reports.css',
                'resources/css/pages/settings.css',
                'resources/css/pages/shares.css',
                'resources/css/pages/workspace.css',
                'resources/js/app.js',
                'resources/js/components/avatar-fallback.js',
                'resources/js/components/realtime-sync.js',
                'resources/js/pages/board/admin-assignment.js',
                'resources/js/pages/daily-logs/index.js',
                'resources/js/pages/daily-logs/categories.js',
                'resources/js/pages/employees/index.js',
                'resources/js/pages/admin/approvals.js',
                'resources/js/pages/admin/audit.js',
                'resources/js/pages/mytasks/index.js',
                'resources/js/pages/work-board/department.js',
                'resources/js/pages/meetings/index.js',
                'resources/js/pages/notifications.js',
                'resources/js/pages/reports/index.js',
                'resources/js/pages/reports/employee.js',
                'resources/js/pages/reports/my.js',
                'resources/js/pages/reports/operational.js',
                'resources/js/pages/settings/index.js',
                'resources/js/pages/shares/index.js',
                'resources/js/pages/workspace/board-list.js',
                'resources/js/pages/workspace/index.js',
            ],
            refresh: true,
        }),
        tailwindcss(),
    ],
    server: {
        watch: {
            ignored: ['**/storage/framework/views/**'],
        },
    },
});
