(() => {
    const root = document.querySelector('[data-workspace]'); const kanban = root?.querySelector('[data-kanban]'); if (!root || !kanban) return;
    const refresh = () => kanban.querySelectorAll('[data-kanban-panel]').forEach((panel) => { let total = 0; panel.querySelectorAll('[data-kanban-column]').forEach((column) => { const count = column.querySelectorAll('[data-kanban-card]').length; column.querySelector('[data-kanban-count]').textContent = count; total += count; }); if (!panel.hidden) kanban.querySelector('[data-kanban-project-count]').textContent = `${total} งาน`; });
    kanban.querySelector('[data-kanban-project]')?.addEventListener('change', (event) => { kanban.querySelectorAll('[data-kanban-panel]').forEach((panel) => panel.hidden = panel.dataset.kanbanPanel !== event.target.value); refresh(); });
    document.addEventListener('click', (event) => { const trigger = event.target.closest('[data-open-kanban-task]'); if (!trigger) return; event.preventDefault(); root.querySelector(`[data-row][data-id="${trigger.dataset.openKanbanTask}"] [data-open-task-modal]`)?.click(); });
    refresh();
    document.addEventListener('mytasks:changed', (event) => { const task = event.detail; const card = kanban.querySelector(`[data-kanban-card][data-id="${task.id}"]`); if (!card) return; card.dataset.status = task.status; card.dataset.priority = task.priority; card.className = `mytasks-kanban__card priority-${task.priority}`; card.querySelector('[data-kanban-title]').textContent = task.topic; kanban.querySelector(`[data-kanban-column="${task.status}"] .mytasks-kanban__cards`)?.append(card); refresh(); });
    let dragged = null;
    kanban.querySelectorAll('[data-kanban-card]').forEach((card) => { card.draggable = true; card.querySelectorAll('*').forEach((item) => item.draggable = true); card.addEventListener('dragstart', (event) => { dragged = card; event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', card.dataset.id); card.classList.add('is-dragging'); }); card.addEventListener('dragend', () => { card.classList.remove('is-dragging'); dragged = null; }); });
    kanban.querySelectorAll('[data-kanban-column]').forEach((column) => { const dropZone = column.querySelector('.mytasks-kanban__cards'); const allowDrop = (event) => { event.preventDefault(); event.dataTransfer.dropEffect = 'move'; column.classList.add('is-drop-target'); }; const drop = (event) => { event.preventDefault(); column.classList.remove('is-drop-target'); if (!dragged) return; const card = dragged; const status = Number(column.dataset.kanbanColumn); const previousZone = card.parentElement; const previousStatus = card.dataset.status; if (Number(previousStatus) === status) return; card.dataset.status = String(status); dropZone?.append(card); refresh(); fetch(root.dataset.statusTemplate.replace('__ID__', card.dataset.id), {method:'PATCH', headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]')?.content || ''}, body:JSON.stringify({job_status:status})}).then(async (response) => { if (response.ok) return; const data = await response.json().catch(() => ({})); card.dataset.status = previousStatus; previousZone?.append(card); refresh(); window.Swal?.fire({icon:'error', title:'เปลี่ยนสถานะไม่สำเร็จ', text:data.message || 'กรุณาลองใหม่'}); }).catch(() => { card.dataset.status = previousStatus; previousZone?.append(card); refresh(); }); }; [column, dropZone].filter(Boolean).forEach((target) => { target.addEventListener('dragover', allowDrop); target.addEventListener('dragenter', allowDrop); target.addEventListener('drop', drop); target.addEventListener('dragleave', (event) => { if (!column.contains(event.relatedTarget)) column.classList.remove('is-drop-target'); }); }); });
    
})();
