<!doctype html>
<html lang="th">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Smart Goal — Notion Database Demo</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Thai:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <style>{!! file_get_contents(resource_path('css/pages/tasks-demo-notion.css')) !!}</style>
</head>
<body><div class="notion-demo" data-demo>
<aside class="sidebar"><div class="brand"><span>SG</span><div><b>Smart Goal</b><small>BY PREMIUMCARE</small></div></div><nav><small>พื้นที่ของฉัน</small><a class="active"><i class="bi bi-table"></i>งานของฉัน</a><a><i class="bi bi-bar-chart"></i>รายงานของฉัน</a><a><i class="bi bi-bell"></i>การแจ้งเตือน <em>3</em></a><a><i class="bi bi-gear"></i>ตั้งค่า</a></nav><div class="profile"><i>พ</i><div><b>พันกร ศรีทอน</b><small>พนักงาน · IT</small></div><button title="ออกจากระบบ"><i class="bi bi-box-arrow-right"></i></button></div></aside>
<main><header><button class="mobile-menu" data-menu><i class="bi bi-list"></i></button><span>พื้นที่ของฉัน</span><i class="bi bi-chevron-right"></i><b>งานของฉัน</b><div class="header-right"><button title="การแจ้งเตือน"><i class="bi bi-bell"></i><em>3</em></button><span>พนักงาน</span></div></header>
<section class="workspace"><div class="title-row"><div><small>SMART GOAL WORKSPACE</small><h1>งานของฉัน</h1><p>ติดตามงาน แก้ไขข้อมูล และจัดลำดับสิ่งที่ต้องทำได้ในหน้าเดียว</p></div><button class="primary" data-add><i class="bi bi-plus-lg"></i>เพิ่มงานใหม่</button></div>
<div class="views"><button class="active"><i class="bi bi-table"></i>ตารางทั้งหมด</button><button><i class="bi bi-layout-three-columns"></i>บอร์ด</button><button><i class="bi bi-list-ul"></i>รายการ</button><button title="เพิ่มมุมมอง"><i class="bi bi-plus"></i></button></div>
<section class="database-shell"><div class="toolbar"><label class="search"><i class="bi bi-search"></i><input data-search placeholder="ค้นหาทุกคอลัมน์..."></label><div class="tools"><label>จัดกลุ่มตาม<select data-group><option value="status">สถานะ</option><option value="project">โปรเจกต์</option><option value="assignee">ผู้รับผิดชอบ</option><option value="priority">ความสำคัญ</option></select></label><button data-filter><i class="bi bi-funnel"></i>ตัวกรอง <i class="count" hidden>0</i></button><button data-sort><i class="bi bi-sort-down"></i>เรียงกำหนดส่ง</button></div><div class="filters" data-filters hidden><b>แสดงเฉพาะ</b><label><input type="checkbox" value="ล่าช้า">งานล่าช้า</label><label><input type="checkbox" value="รอตรวจสอบ">รอตรวจสอบ</label><label><input type="checkbox" value="กำลังทำ">กำลังทำ</label><button data-clear>ล้างตัวกรอง</button></div></div><div class="scroll"><div class="database" data-database></div></div><footer><button data-add><i class="bi bi-plus"></i>เพิ่มงาน</button><span>Demo เท่านั้น · บันทึกข้อมูลจำลองไว้ในเบราว์เซอร์</span></footer></section></section></main>
<aside class="detail" data-detail><div class="detail-top"><span>รายละเอียดงาน</span><button data-close><i class="bi bi-x-lg"></i></button></div><article><small data-project></small><h2 contenteditable data-title></h2><dl><dt>สถานะ</dt><dd data-status></dd><dt>ผู้รับผิดชอบ</dt><dd data-assignee></dd><dt>กำหนดส่ง</dt><dd data-due></dd><dt>ความสำคัญ</dt><dd data-priority></dd></dl><hr><h3>รายละเอียด</h3><p contenteditable data-description></p><h3>งานย่อย</h3><label class="check"><input type="checkbox" checked>ตรวจสอบความต้องการและข้อมูลที่ได้รับ</label><label class="check"><input type="checkbox">ส่งผลงานให้ผู้รับผิดชอบตรวจสอบ</label><button class="plain"><i class="bi bi-plus"></i>เพิ่มงานย่อย</button><h3>กิจกรรมล่าสุด</h3><div class="activity"><i>พ</i><p><b>พันกร ศรีทอน</b> อัปเดตความคืบหน้า<br><small>วันนี้ เวลา 10:24 น.</small></p></div></article></aside><div class="backdrop" data-backdrop></div><div class="toast" data-toast><i class="bi bi-check-circle-fill"></i><span>บันทึกแล้ว</span></div>
</div><script>{!! file_get_contents(resource_path('js/tasks-demo-notion.js')) !!}</script></body></html>
